﻿-- EXCLUINDO TABELAS, CASO EXISTAM
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'MENSAGEM')
	DROP TABLE MENSAGEM;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'ENTREGA')
	DROP TABLE ENTREGA;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'ATIVIDADEVINCULADA')
	DROP TABLE ATIVIDADEVINCULADA;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'ATIVIDADE')
	DROP TABLE ATIVIDADE;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'SOLICITACAOMATRICULA')
	DROP TABLE SOLICITACAOMATRICULA;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'DISCIPLINAOFERTADA')
	DROP TABLE DISCIPLINAOFERTADA;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'DISCIPLINA')
	DROP TABLE DISCIPLINA;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'ALUNO')
	DROP TABLE ALUNO;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'PROFESSOR')
	DROP TABLE PROFESSOR;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'COORDENADOR')
	DROP TABLE COORDENADOR;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'USUARIO')
	DROP TABLE USUARIO;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'CURSO')
	DROP TABLE CURSO;

-- TABELA USUARIO
CREATE TABLE USUARIO
(
	ID				INT			IDENTITY,
	LOGIN			VARCHAR(30) NOT NULL,
	SENHA			CHAR(8)		NOT NULL,
	DTEXPIRACAO		DATE		NOT NULL	CONSTRAINT DF_USU_DTEXP	DEFAULT ('1900/01/01'), 

	CONSTRAINT PK_USU		PRIMARY KEY (ID),
	CONSTRAINT UQ_USU_LOGIN	UNIQUE (LOGIN),
	CONSTRAINT CK_USU_SENHA	CHECK ( LEN(SENHA) = 8) -- EXTRA: SENHA OBRIGATORIAMENTE TERA 8 CARACTERES
);

-- TABELA ALUNO
CREATE TABLE ALUNO
(
	ID			INT				IDENTITY,
	IDUSUARIO	INT				NOT NULL,
	NOME		VARCHAR(50)		NOT NULL,
	EMAIL		VARCHAR(50)		NOT NULL,
	CELULAR		CHAR(11)		NOT NULL,
	RA			CHAR(7)			NOT NULL, 
	FOTO		VARCHAR(100)	,

	CONSTRAINT PK_ALUNO		PRIMARY KEY (ID),
	CONSTRAINT UQ_ALU_EMAIL UNIQUE (EMAIL),
	CONSTRAINT UQ_ALU_CELUL UNIQUE (CELULAR),
	CONSTRAINT UQ_ALU_RA	UNIQUE (RA) -- EXTRA: RA NÃO PODE DUPLICAR
);

--TABELA COORDENADOR
CREATE TABLE COORDENADOR
(
	ID			SMALLINT				IDENTITY,
	IDUSUARIO	INT				NOT NULL,
	NOME		VARCHAR(50)		NOT NULL,
	EMAIL		VARCHAR(50)		NOT NULL,
	CELULAR		CHAR(11)		NOT NULL

	CONSTRAINT PK_COORD		PRIMARY KEY (ID),
	CONSTRAINT UQ_COO_EMAIL UNIQUE (EMAIL),
	CONSTRAINT UQ_COO_CELUL UNIQUE (CELULAR)
);

--TABELA PROFESSOR
CREATE TABLE PROFESSOR
(
	ID			SMALLINT		IDENTITY,
	IDUSUARIO	INT,
	NOME		VARCHAR(50)		NOT NULL,  -- EXTRA: AJUSTE DO MODELO, FALTAVA O NOME DO PROF
	EMAIL		VARCHAR(50)		NOT NULL,
	CELULAR		CHAR(11)		NOT NULL,
	APELIDO		VARCHAR(50)		NOT NULL

	CONSTRAINT PK_PROFE		PRIMARY KEY (ID),
	CONSTRAINT UQ_PRO_EMAIL UNIQUE (EMAIL),
	CONSTRAINT UQ_PRO_CELUL UNIQUE (CELULAR)
);

-- TABELA DISCIPLINA
CREATE TABLE DISCIPLINA
(
	ID					     SMALLINT		IDENTITY,
	NOME					 VARCHAR(100)	NOT NULL,
	DATA					 DATE			NOT NULL CONSTRAINT DF_DIS_DATA	DEFAULT (GETDATE()),
	STATUS					 VARCHAR(10)	NOT NULL CONSTRAINT DF_DIS_STAT	DEFAULT ('ABERTA'),
	PLANODEENSINO			 VARCHAR(1000)	NOT NULL,
	CARGAHORARIA			 TINYINT		NOT NULL,
	COMPETENCIAS			 VARCHAR(1000)	NOT NULL,
	HABILIDADES				 VARCHAR(1000)	NOT NULL,
	EMENTA					 VARCHAR(1000)	NOT NULL,
	CONTEUDOPROGRAMATICO	 VARCHAR(1000)	NOT NULL,
	BIBLIOGRAFIABASICA		 VARCHAR(1000)	NOT NULL,
	BIBLIOGRAFIACOMPLEMENTAR VARCHAR(1000)	NOT NULL,
	PERCENTUALPRATICO		 TINYINT		NOT NULL,
	PERCENTUALTEORICO		 TINYINT		NOT NULL,
	IDCOORDENADOR			 SMALLINT		NOT NULL,
	
	CONSTRAINT PK_DISCI		PRIMARY KEY (ID),
	CONSTRAINT UQ_DIS_NOME	UNIQUE (NOME),
	CONSTRAINT CK_DIS_STAT	CHECK ( STATUS IN ('ABERTA', 'FECHADA' )),
	CONSTRAINT CK_DIS_CARG	CHECK ( CARGAHORARIA IN (40,80)),
	CONSTRAINT CK_DIS_PERP	CHECK ( PERCENTUALPRATICO BETWEEN 0 and 100),
	CONSTRAINT CK_DIS_PERT	CHECK ( PERCENTUALTEORICO BETWEEN 0 AND 100),
	CONSTRAINT CK_DIS_PERC	CHECK ( PERCENTUALTEORICO + PERCENTUALPRATICO = 100 )  -- EXTRA: PERC PRATICO + TEORICO = 100%
);

-- TABELA DISCIPLINA OFERTADA
CREATE TABLE DISCIPLINAOFERTADA
(
	ID					    INT			IDENTITY,
	IDCOORDENADOR			SMALLINT	NOT NULL,
	DTINICIOMATRICULA		DATE,
	DTFIMMATRICULA			DATE,
	IDDISCIPLINA			SMALLINT	NOT NULL,
	IDCURSO					TINYINT		NOT NULL,
	ANO						SMALLINT	NOT NULL,
	SEMESTRE				TINYINT		NOT NULL,
	TURMA					CHAR(1)		NOT NULL,
	IDPROFESSOR				SMALLINT,
	METODOLOGIA				VARCHAR(1000),
	RECURSOS				VARCHAR(1000),
	CRITERIOAVALIACAO		VARCHAR(1000),
	PLANODEAULAS			VARCHAR(1000),

	CONSTRAINT PK_DOFER		PRIMARY KEY (ID),
	CONSTRAINT CK_DOFER_ANO CHECK(ANO BETWEEN 1900 AND 2100),
	CONSTRAINT CK_DOFER_SEM CHECK(SEMESTRE IN (1,2)),
	CONSTRAINT CK_DOFER_TUR CHECK(TURMA BETWEEN 'A' AND 'Z'),
	CONSTRAINT CK_DOFER_PRO CHECK 
		(CASE 
			WHEN IDPROFESSOR  IS NULL 
			THEN 1
			WHEN IDPROFESSOR  IS NOT NULL AND METODOLOGIA IS NOT NULL AND
				 RECURSOS	  IS NOT NULL AND CRITERIOAVALIACAO IS NOT NULL AND
				 PLANODEAULAS IS NOT NULL 
			THEN 1
			ELSE 0
		END = 1), -- EXTRA VALIDAÇÃO SE ESTIVER SEM PROF OK. CASO PROF TEM QUE TER METODOLOGIA, RECURSO, CRITERIO E PLANO.
	CONSTRAINT UQ_DOFER_COM	UNIQUE (IDDISCIPLINA, IDCURSO, ANO, SEMESTRE, TURMA)
);				 

--TABELA CURSO
CREATE TABLE CURSO
(
	ID		TINYINT		IDENTITY,
	NOME	VARCHAR(50)	NOT NULL,

	CONSTRAINT PK_CURSO			PRIMARY KEY (ID),
	CONSTRAINT UQ_CURSO_NOME	UNIQUE (NOME)
);


-- TABELA SOLICITACAO MATRICULA
CREATE TABLE SOLICITACAOMATRICULA
(
	ID				INT			IDENTITY,
	IDALUNO			INT			NOT NULL,
	IDDOFERTADA		INT			NOT NULL,
	DTSOLICITACAO	DATETIME	NOT NULL CONSTRAINT DF_SMATRI_DT DEFAULT (GETDATE()),
	IDCOORDENADOR	SMALLINT, 
	STATUS			VARCHAR(15)	NOT NULL CONSTRAINT DF_SMATRI_ST DEFAULT ('SOLICITADA'),

	CONSTRAINT	PK_SMATRI	 PRIMARY KEY (ID),
	CONSTRAINT	CK_SMATRI_ST CHECK (STATUS IN ('SOLICITADA', 'APROVADA','REJEITADA', 'CANCELADA' ))
);

-- TABELA ATIVIDADE
CREATE TABLE ATIVIDADE
(
	ID				INT				IDENTITY,
	TITULO			VARCHAR(30)		NOT NULL,
	DESCRICAO		VARCHAR(100),
	CONTEUDO		VARCHAR(8000)	NOT NULL,
	TIPO 			VARCHAR(15)		NOT NULL, 
	EXTRAS			VARCHAR(100),
	IDPROFESSOR		SMALLINT,

	CONSTRAINT	PK_ATIVIDADE	PRIMARY KEY (ID),
	CONSTRAINT	UQ_ATIVI_TITU	UNIQUE (TITULO),	 
	CONSTRAINT	CK_ATIVI_TIPO	CHECK (TIPO IN ('RESPOSTA ABERTA', 'TESTE')),
);

-- TABELA ATIVIDADE VINCULADA
CREATE TABLE ATIVIDADEVINCULADA
(
	ID				INT			 IDENTITY,
	IDATIVIDADE		INT			 NOT NULL,
	IDPROFESSOR		SMALLINT	 NOT NULL,
	IDDOFERTADA		INT			 NOT NULL,
	ROTULO			VARCHAR(100) NOT NULL,
	STATUS			VARCHAR(15)	 NOT NULL,
	DTINIRESPOSTA	DATETIME	 NOT NULL,
	DTFIMRESPOSTA	DATETIME	 NOT NULL,

	CONSTRAINT	PK_AVINCULADA	PRIMARY KEY (ID),
	CONSTRAINT	UQ_AVINC		UNIQUE (ROTULO, IDATIVIDADE, IDDOFERTADA),
	CONSTRAINT  CK_AVINC_STAT	CHECK (STATUS IN ('DISPONIBILIZADA','ABERTA', 'FECHADA','ENCERRADA','PRORROGADA'))
);

-- TABELA ENTREGA
CREATE TABLE ENTREGA
(
	ID				INT				IDENTITY,
	IDALUNO			INT				NOT NULL,
	IDAVINCULADA	INT				NOT NULL,
	TITULO			VARCHAR(100)	NOT NULL,
	RESPOSTA		VARCHAR(8000)	NOT NULL,
	DTENTREGA		DATETIME		NOT NULL CONSTRAINT DF_ENTRE_DTEN DEFAULT (GETDATE()),
	STATUS			VARCHAR(10)		NOT NULL CONSTRAINT DF_ENTRE_STAT	DEFAULT	('ENTREGUE'),
	IDPROFESSOR		SMALLINT,
	NOTA			DECIMAL(4,2),
	DTAVALIACAO		DATETIME,
	OBS				VARCHAR(500),

	CONSTRAINT	PK_ENTREGA		PRIMARY KEY (ID),
	CONSTRAINT  UQ_ENTRE		UNIQUE (IDALUNO, IDAVINCULADA),
	CONSTRAINT  CK_ENTRE_STAT	CHECK (STATUS IN ('ENTREGUE','CORRIGIDO')),
	CONSTRAINT  CK_ENTRE_NOTA	CHECK (NOTA BETWEEN 0 AND 10),
	CONSTRAINT	CK_ENTRE_CORR	CHECK
		(CASE 
			WHEN IDPROFESSOR  IS NULL 
			THEN 1
			WHEN IDPROFESSOR  IS NOT NULL AND 
				 NOTA IS NOT NULL AND
				 DTAVALIACAO = GETDATE() AND 
				 STATUS = 'CORRIGIDO'
			THEN 1
			ELSE 0
		END = 1), -- EXTRA VALIDAÇÃO SE ESTIVER SEM PROF OK. CASO PROF CORRIGIR, TEM QUE TER NOTA E DATA TEM QUE SER DATA/HORA ATUAL.
)

-- TABELA MENSAGEM
CREATE TABLE MENSAGEM
(
		ID				INT				IDENTITY,
		IDALUNO			INT				NOT NULL,
		IDPROFESSOR		SMALLINT		NOT NULL,
		ASSUNTO			VARCHAR(100)	NOT NULL,
		REFERENCIA		VARCHAR(100)	NOT NULL,
		CONTEUDO		VARCHAR(500)	NOT NULL,
		STATUS			VARCHAR(10)		NOT NULL CONSTRAINT DF_MENSA_STAT DEFAULT 'ENVIADO',
		DTENVIO			DATETIME		NOT NULL CONSTRAINT DF_MENSA_DTEN DEFAULT GETDATE(),
		DTRESPOSTA		DATETIME,
		RESPOSTA		VARCHAR(500),
		
		CONSTRAINT	PK_MENSAGEM		PRIMARY KEY (ID),
		CONSTRAINT	CK_MENSA_STAT	CHECK (STATUS IN ( 'ENVIADO', 'LIDO', 'RESPONDIDO' )),
		CONSTRAINT	CK_MENSA_RESP	CHECK
		(CASE 
			WHEN DTRESPOSTA  IS NULL 
			THEN 1
			WHEN DTRESPOSTA  IS NOT NULL AND 
				 RESPOSTA IS NOT NULL AND
				 STATUS = 'RESPONDIDO'
			THEN 1
			ELSE 0
		END = 1), -- EXTRA VALIDAÇÃO SE ESTIVER SEM DTRESPOSTA OK. CASO MENSAGEM RESPONDIDA, TEM QUE TER DTRESPOSTA, RESPOSTA E STATUS TEM QUE SER RESPONDIDO.
)

-- INCLUINDO AS FKs

ALTER TABLE COORDENADOR ADD
	CONSTRAINT FK_COORD_USU	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (ID);

ALTER TABLE PROFESSOR ADD
	CONSTRAINT FK_PROFE_USU	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (ID);

ALTER TABLE ALUNO ADD
	CONSTRAINT FK_ALUNO_USU	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (ID);

ALTER TABLE DISCIPLINA ADD
	CONSTRAINT FK_DISCI_COORD FOREIGN KEY (IDCOORDENADOR) REFERENCES COORDENADOR (ID);

ALTER TABLE DISCIPLINAOFERTADA ADD
	CONSTRAINT FK_DOFER_COORD FOREIGN KEY (IDCOORDENADOR) REFERENCES COORDENADOR (ID),
	CONSTRAINT FK_DOFER_DISCI FOREIGN KEY (IDDISCIPLINA)  REFERENCES DISCIPLINA (ID),
	CONSTRAINT FK_DOFER_CURSO FOREIGN KEY (IDCURSO)		  REFERENCES CURSO (ID),
	CONSTRAINT FK_DOFER_PROFE FOREIGN KEY (IDPROFESSOR)   REFERENCES PROFESSOR (ID);

ALTER TABLE SOLICITACAOMATRICULA ADD
	CONSTRAINT FK_SMATR_COORD FOREIGN KEY (IDCOORDENADOR) REFERENCES COORDENADOR (ID),
	CONSTRAINT FK_SMATR_DISCI FOREIGN KEY (IDDOFERTADA)   REFERENCES DISCIPLINAOFERTADA (ID),
	CONSTRAINT FK_SMATR_ALUNO FOREIGN KEY (IDALUNO)		  REFERENCES ALUNO (ID);

ALTER TABLE ATIVIDADE ADD
	CONSTRAINT FK_ATIV_PROFE FOREIGN KEY (IDPROFESSOR)   REFERENCES PROFESSOR (ID);

ALTER TABLE ATIVIDADEVINCULADA ADD
	CONSTRAINT FK_AVINC_ATIVI FOREIGN KEY (IDATIVIDADE)	  REFERENCES ATIVIDADE (ID),
	CONSTRAINT FK_AVINC_DISCI FOREIGN KEY (IDDOFERTADA)   REFERENCES DISCIPLINAOFERTADA (ID),
	CONSTRAINT FK_AVINC_PROFE FOREIGN KEY (IDPROFESSOR)   REFERENCES PROFESSOR (ID);

ALTER TABLE ENTREGA ADD
	CONSTRAINT FK_ENTRE_PROFE FOREIGN KEY (IDPROFESSOR)   REFERENCES PROFESSOR (ID),
	CONSTRAINT FK_ENTRE_AVINC FOREIGN KEY (IDAVINCULADA)  REFERENCES ATIVIDADEVINCULADA (ID),
	CONSTRAINT FK_ENTRE_ALUNO FOREIGN KEY (IDALUNO)		  REFERENCES ALUNO (ID);

ALTER TABLE MENSAGEM ADD
	CONSTRAINT FK_MENSA_PROFE FOREIGN KEY (IDPROFESSOR)   REFERENCES PROFESSOR (ID),
	CONSTRAINT FK_MENSA_ALUNO FOREIGN KEY (IDALUNO)		  REFERENCES ALUNO (ID);


	---- INSERT ------------------------------------------------------
	--ALUNOS
INSERT INTO USUARIO (LOGIN, SENHA) VALUES
('GILSON.ALMEIDA', 'G1501375'),
('SEBASTIAO.RODRIGUES','S1602440'),
('VALDIR.CASTRO','V1602396'),
('LUIZ.MELO','L1701777'),
('FRANCISCO.JESUS','F1602405'),
('NELSON.MOREIRA','N1602128'),
('RAIMUNDO.MORAES','R1602230'),
('FABIO.MOURA','F1601249'),
('ANDRE.COSTA','A1701595'),
('MARCIO.BATISTA','M1601576'),
('VINICIUS.CONCEICAO','V1501650'),
('JOAO.SOUSA','J1702249'),
('ANTONIO.MAGALHAES','A1702525'),
('JOSE.MORAIS','J1501148'),
('JONATHAN.FILHO','J1502810'),
('PAULO.MELO','P1602770'),
('ALESSANDRO.DIAS','A1602697'),
('EVERTON.MARTINS','E1602173'),
('EDSON.FERNANDES','E1601713'),
('EMERSON.MENEZES','E1602326'),
('CICERO.SANTANA','C1501257'),
('MICHELE.GARCIA','M1501464'),
('DOUGLAS.XAVIER','D1502465'),
('RODRIGO.GOMES','R1502808'),
('ALEXANDRE.DIAS','A1601975'),
('MAURO.CARVALHO','M1702530'),
('EDUARDO.VIEIRA','E1602305'),
('FABRICIO.MACHADO','F1701582'),
('DANIEL.ROCHA','D1501352'),
('JEAN.NEVES','J1701910'),
('TAMIRES.CAVALCANTE','T1701166'),
('DIEGO.NETO','D1502850'),
('MARCELO.SANTOS','M1602346'),
('LEONARDO.CUNHA','L1601418'),
('ALAN.AGUIAR','A1702476'),
('ADRIANA.MACHADO','A1702619'),
('MARIA.NASCIMENTO','M1502116'),
('ANA.FARIAS','A1702648'),
('RENATA.COSTA','R1702436'),
('VERA.CARDOSO','V1602388'),
('ELAINE.MENDES','E1701548'),
('JESSICA.PEREIRA','J1502514'),
('PRISCILA.FARIAS','P1601584'),
('ROSANGELA.RIBEIRO','R1502845'),
('LUCIANA.FERREIRA','L1601609'),
('ELAINE.BRAGA','E1702717'),
('ANTONIA.FILHO','A1602719'),
('PATRICIA.MORAIS','P1601963'),
('MARIA.MORAES','M1602611'),
('CLAUDIA.MOURA','C1601449')

--PROFESSORES
INSERT INTO USUARIO (LOGIN, SENHA) VALUES
('ALAN.OLIVEIRA','AO123456'),
('ALBERTO.JUNIOR','AJ123456'),
('ALEXANDRE.RANGEL','AR123456'),
('ALEXANDRE.MARTINS','AM123456'),
('ALVARO.TAKEI','AT123456'),
('ANA.SANTOS','AS123456'),
('BRUNO.KALKEVICIUS','AK123456'),
('CEZAR.BELLINI','CB123456'),
('EDSON.SILVA','ES123456'),
('EDSON.TSUKIMOTO','ET123456'),
('EDUARDO.QUEIROZ','EQ123456'),
('EMILIO.RESENDE','ER123456'),
('FELIPE.DIAS','FD123456'),
('FERNANDO.ZUHER','FZ123456'),
('FRANCESCA.ROMANELLI','FR123456'),
('GISELDA.PEREIRA','GP123456'),
('GUILHERME.LOHMANN','GL123456'),
('GUSTAVO.FERREIRA','GF123456'),
('ILANA.CONCILIO','IC123456'),
('IZA.MELAO','IM123456'),
('JOAO.COUTINHO','JC123456'),
('JOSE.PRADO','JP123456'),
('LEONARDO.TAKUNO','LT123456'),
('LUCAS.GONÇALVES','LG123456'),
('LUCIANO.CROCCO','LC123456'),
('MARCEL.PIRES','MP123456'),
('MARCELO.SILVA','MS123456'),
('MARCELO.TERRA','MT123456'),
('MARCO.JEUNON','MJ123456'),
('OSVALDO.TAKAI','OT123456'),
('PEDRO.PRADO','PP123456'),
('PLINIO.FILHO','PF123456'),
('RENATO.SANTOS','RS123456'),
('RODRIGO.PIASSI','RP123456'),
('SERGIO.BRUZETTI','SB123456'),
('VANDERSON.BOSSI','VB123456'),
('VICTOR.OLIVEIRA','VO123456'),
('VLADIMIR.CHAGAS','VC123456'),
('BRUNO.LIMA','BL123456'),
('ALAN.CARVALHO','AC123456'),
('AYAO.OKAMOTO','AO123456')

--CADASTRANDO ALUNOS
INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(1, 'GILSON FERNANDES ALMEIDA','gf_almeida@impacta.com.br','11987654321','1501375'),
(2,'SEBASTIAO.RODRIGUES','sd_rodrigues@impacta.com.br','11987654123','1602440'),
(3,'VALDIR.CASTRO','vg_castro@impacta.com.br','11936547892','1602396'),
(4,'LUIZ.MELO','ld_melo@impacta.com.br','11932541785','1701777'),
(5,'FRANCISCO.JESUS','fd_jesus@impacta.com.br','11932145698','1602405'),
(6,'NELSON.MOREIRA','nf_moreira@impacta.com.br','11965231452','1602128'),
(7,'RAIMUNDO.MORAES','rv_moraes@impacta.com.br','11974589856','1602230'),
(8,'FABIO.MOURA','ff_moura@impacta.com.br','11958965412','1601249'),
(9,'ANDRE.COSTA','as_costa@impacta.com.br','11932897852','1701595'),
(10,'MARCIO.BATISTA','md_batista@impacta.com.br','11974523658','1601576'),
(11,'VINICIUS.CONCEICAO','vs_conceicao@impacta.com.br','11945653223','1501650'),
(12,'JOAO.SOUSA','ja_sousa@impacta.com.br','11936587447','1702249'),
(13,'ANTONIO.MAGALHAES','af_magalhaes@impacta.com.br','11936699663','1702525'),
(14,'JOSE.MORAIS','jl_morais@impacta.com.br','11945788989','1501148'),
(15,'JONATHAN.FILHO','js_filho@impacta.com.br','11965455665','1502810'),
(16,'PAULO.MELO','pr_melo@impacta.com.br','11998787889','1602770'),
(17,'ALESSANDRO.DIAS','a_dias@impacta.com.br','11914455221','1602697'),
(18,'EVERTON.MARTINS','ed_martins@impacta.com.br','11932569874','1602173'),
(19,'EDSON.FERNANDES','ea_fernandes@impacta.com.br','11998777445','1601713'),
(20,'EMERSON.MENEZES','eg_menezes@impacta.com.br','11932144569','1602326'),
(21,'CICERO.SANTANA','cp_santana@impacta.com.br','11974412558','1501257'),
(22,'MICHELE.GARCIA','ms_garcia@impacta.com.br','11932211449','1501464'),
(23,'DOUGLAS.XAVIER','dg_xavier@impacta.com.br','11995577112','1502465'),
(24,'RODRIGO.GOMES','rr_gomes@impacta.com.br','11935599774','1502808'),
(25,'ALEXANDRE.DIAS','ad_dias@impacta.com.br','11935698745','1601975'),
(26,'MAURO.CARVALHO','md_carvalho@impacta.com.br','11932569876','1702530'),
(27,'EDUARDO.VIEIRA','e_vieira@impacta.com.br','11965871983','1602305'),
(28,'FABRICIO.MACHADO','fr_machado@impacta.com.br','11937911973','1701582'),
(29,'DANIEL.ROCHA','df_rocha@impacta.com.br','11971397139','1501352'),
(30,'JEAN.NEVES','jd_neves@impacta.com.br','11956981254','1701910'),
(31,'TAMIRES.CAVALCANTE','tp_cavalcante@impacta.com.br','11928391728','1701166'),
(32,'DIEGO.NETO','dr_neto@impacta.com.br','11981387292','1502850'),
(33,'MARCELO.SANTOS','md_santos@impacta.com.br','11946288264','1602346'),
(34,'LEONARDO.CUNHA','lr_cunha@impacta.com.br','11954565852','1601418'),
(35,'ALAN.AGUIAR','aa_aguiar@impacta.com.br','11948424643','1702476'),
(36,'ADRIANA.MACHADO','af_machado@impacta.com.br','11964626869','1702619'),
(37,'MARIA.NASCIMENTO','mb_nascimento@impacta.com.br','11934268486','1502116'),
(38,'ANA.FARIAS','af_farias@impacta.com.br','11979787574','1702648'),
(39,'RENATA.COSTA','rv_costa@impacta.com.br','11934185759','1702436'),
(40,'VERA.CARDOSO','v_cardoso@impacta.com.br','11920010405','1602388'),
(41,'ELAINE.MENDES','eb_mendes@impacta.com.br','11905871236','1701548'),
(42,'JESSICA.PEREIRA','jd_pereira@impacta.com.br','11950247820','1502514'),
(43,'PRISCILA.FARIAS','pm_farias@impacta.com.br','11990321456','1601584'),
(44,'ROSANGELA.RIBEIRO','rp_ribeiro@impacta.com.br','11901245887','1502845'),
(45,'LUCIANA.FERREIRA','lm_ferreira@impacta.com.br','11910369880','1601609'),
(46,'ELAINE.BRAGA','es_braga@impacta.com.br','11930214587','1702717'),
(47,'ANTONIA.FILHO','af_filho@impacta.com.br','11901236547','1602719'),
(48,'PATRICIA.MORAIS','pd_morais@impacta.com.br','11990807040','1601963'),
(49,'MARIA.MORAES','ma_moraes@impacta.com.br','11989837754','1602611'),
(50,'CLAUDIA.MOURA','cd_moura@impacta.com.br','11970309093','1601449')

--CADASTRANDO COORDENADOR
INSERT INTO COORDENADOR (IDUSUARIO, NOME, EMAIL, CELULAR) VALUES
(56, 'ANA CRISTINA DOS SANTOS', 'ac_santos@impacta.com.br', '11970585032'),
(65, 'FRANCESCA ROMANELLI', 'f_romanelli@impacta.com.br', '11920114498'),
(80, 'OSVALDO KOTARO TAKAI', 'ok_takai@impacta.com.br', '11947596872'),
(89, 'BRUNO LUIS SOARES DE LIMA','BL_SOARES@IMPACTA.COM.BR','11965897854'),
(90, 'ALAN HENRIQUE PRADO DE CARVALHO','AH_PRADO@IMPACTA.COM.BR','11932569874'),
(91, 'AYAO OKAMOTO','AY_OKAMOTO@IMPACTA.COM.BR','11912332114')

--CADASTRANDO CURSO
INSERT INTO CURSO VALUES
('ADMINISTRACAO'),
('ANÁLISE E DESENVOLVIMENTO DE SISTEMAS'),
('ANALISE E DESENVOLVIMENTO DE SISTEMA EAD'),
('BANCO DE DADOS'),
('ENGENHARIA DA COMPUTACAO'),
('GESTAO DA TECNOLOGIA DA INFORMACAO'),
('JOGOS DIGITAIS'),
('PROCESSOS GERENCIAIS'),
('PRODUCAO MULTIMIDIA'),
('REDES DE COMPUTADORES'),
('SISTEMAS DE INFORMACAO')





--PARTE GETSAM

--CADASTRO DE DISCIPLINA (RAFAEL)

--PARTE PROFESSORES
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO)VALUES
(51, 'ALAN ALVES DE OLIVEIRA', 'aa_oliveira@impacta.com.br', 966543217, 'ALAN'),
(52, 'ALBERTO DE MEDEIROS JUNIOR', 'am_junior@impacta.com.br', 988080841, 'ALBERTO'),
(53, 'ALEXANDRE LEITE RANGEL', 'al_rangel@impacta.com.br', 936351478, 'RANGEL'),
(54, 'ALEXANDRE LOCCI MARTINS', 'al_martins@impacta.com.br', 965012556, 'MARTINS'),
(55, 'ALVARO TOSHIO TAKEI', 'at_takei@impacta.com.br', 970550542, 'ALVARO'),
(56, 'ANA CRISTINA DOS SANTOS', 'ac_santos@impacta.com.br', 970585032, 'ANA'),
(57, 'BRUNO ROBERTO KALKEVICIUS', 'br_kalkevicius@impacta.com.br', 950554978, 'BRUNO'),
(58, 'CEZAR BELLINI', 'c_bellini@impacta.com.br', 956857548, 'CEZAR'),
(59, 'EDSON BENITES SILVA', 'eb_silva@impacta.com.br', 12967845, 'EDSON'),
(60, 'EDSON TIHARU TSUKIMOTO', 'et_tsukimoto@impacta.com.br', 963251577, 'TSUKIMOTO'),
(61, 'EDUARDO LUIS DE QUEIROZ', 'el_queiroz@impacta.com.br', 987756412, 'EDU'),
(62, 'EMILIO MURTA RESENDE', 'em_resende@impacta.com.br', 963524178, 'EMILIO'),
(63, 'FELIPE AUGUSTO ROCHA DIAS', 'fa_dias@impacta.com.br', 963529846, 'FELIPE'),
(64, 'FERNANDO ZUHER', 'f_zuher@impacta.com.br', 963547814, 'FERNANDO'),
(65, 'FRANCESCA ROMANELLI', 'f_romanelli@impacta.com.br', 20114498, 'FRANCESCA'),
(66, 'GISELDA FERNANDA PEREIRA', 'gf_pereira@impacta.com.br', 36359874, 'GISELDA'),
(67, 'GUILHERME GARCEZ LOHMANN', 'gg_lohmann@impacta.com.br', 965874112, 'GUILHERME'),
(68, 'GUSTAVO MENDES FERREIRA', 'gm_ferreira@impacta.com.br', 963524170, 'FERREIRA'),
(69, 'ILANA DE ALMEIDA SOUZA CONCILIO', 'ias_concilio@impacta.com.br', 965847319, 'ILANA'),
(70, 'IZA MELÃO', 'i_melão@impacta.com.br', 978754936, 'IZA'),
(71, 'JOÃO PAULO VENÂNCIO COUTINHO', 'jp_coutinho@impacta.com.br', 987461293, 'JP'),
(72, 'JOSÉ PACHECO DE ALMEIDA PRADO', 'jp_prado@impacta.com.br', 979763454, 'PACHECO'),
(73, 'LEONARDO MASSAYUKI TAKUNO', 'lm_takuno@impacta.com.br', 988659412, 'TAKUNO'),
(74, 'LUCAS MENDES MARQUES GONÇALVES', 'lm_gonçalves@impacta.com.br', 978731246, 'LUCAS'),
(75, 'LUCIANO CROCCO', 'l_crocco@impacta.com.br', 963852744, 'LUCIANO'),
(76, 'MARCEL GINOTTI PIRES', 'mg_pires@impacta.com.br', 944548798, 'MARCEL'),
(77, 'MARCELO CORREIA DA SILVA', 'mc_silva@impacta.com.br', 988080842, 'MARCELO'),
(78, 'MARCELO SANSINI TERRA', 'ms_terra@impacta.com.br', 962518479, 'SANSINI'),
(79, 'MARCO TÚLIO JEUNON', 'mt_jeunon@impacta.com.br', 987785896, 'MARCO'),
(80, 'OSVALDO KOTARO TAKAI', 'ok_takai@impacta.com.br', 947596872, 'TAKAI'),
(81, 'PEDRO FELIPE DO PRADO', 'pf_prado@impacta.com.br', 956847515, 'PEDRO'),
(82, 'PLÍNIO BARBIERI FILHO', 'pb_filho@impacta.com.br', 985861427, 'PLINIO'),
(83, 'RENATO DE SOUZA SANTOS', 'rs_santos@impacta.com.br', 963567841, 'RENATO'),
(84, 'RODRIGO PIASSI', 'r_piassi@impacta.com.br', 963524187, 'RODRIGO'),
(85, 'SÉRGIO EDUARDO DI SANTORO BRUZETTI', 'se_bruzetti@impacta.com.br', 968745212, 'SERGIO'),
(86, 'VANDERSON GOMES BOSSI', 'vg_bossi@impacta.com.br', 963524179, 'VANDERSON'),
(87, 'VICTOR INÁCIO DE OLIVEIRA', 'vi_oliveira@impacta.com.br', 988787843, 'VICTOR'),
(88, 'VLADIMIR CHAGAS', 'v_chagas@impacta.com.br', 978787082, 'VLADIMIR')


INSERT INTO DISCIPLINA(NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('COMUNICAÇÃO E EXPRESSÃO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,2),
('FUNDAMENTOS DA ADMINISTRAÇÃO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DE ADM', 'HABIL DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100,0,2),
('MACROECONOMIA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50,2),
('MATEMATICA APLICADA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('MODELOS DE NEGOCIO E EMPREENDEDORISMO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('PENSAMENTO CRITICO E ETICA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 0, 100, 2),
('ANALISE EXPLORATORIA DE DADOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('CALCULO',  'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('CONTABILIDADE FINANCEIRA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 80, 20, 2),
('MICROECONOMIA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 20, 80, 2),
('RACIOCINIO ANALITICO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('SOCIOLOGIA E POLITICA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 0, 100, 2),
('COMPORTAMENTO ORGANIZACIONAL', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('CONTABILIDADE GERENCIAL', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('GESTÃO DE PROJETOS E PROGRAMAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('INTELIGENCIA DE NEGOCIOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('MATEMATICA FINANCEIRA', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('MODELAGEM DE PROCESSOS DE NEGOCIOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('ADMINISTRAÇÃO FINANCEIRA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('ESTRATEGIA ORGANIZACIONAL', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2), 
('GESTÃO DE MARKETING', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('GESTÃO DE OPERAÇÕES', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('GESTÃO ESTRATEGICA DE PESSOAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('DESIGN THINKING', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('DIREITO APLICADO AO DIREITO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 100, 0, 2),
('GESTÃO DE QUALIDADE', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('MARKETING AVANÇADO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('RESPONSABILIDADE SOCIAL CORPORATIVO', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('STARTUP E INOVAÇÃO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('FINANÇAS CORPORATIVAS E MERCADO DE CAPITAIS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('GESTÃO DA CADEIA DE SUPRIMENTOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('GESTÃO DE CUSTOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('GESTÃO DE PROJETOS DE INOVAÇÃO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('TOMADA DE DECISÃO E NEGOCIAÇÃO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('ESTRATEGIA COMPETITIVA E CORPORATIVA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('JOGOS DE ESTRATEGIAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('GOVERNANÇA CORPORATIVA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('NEGOCIOS INTERNACIONAIS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('SISTEMAS INTEGRADOS DE GESTÃO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
('FUNDAMENTOS DE BANCO DE DADOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('INTRODUCÃO A INTERNET DAS COISAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('LINGUAGEM DE PROGRAMACÃO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
 ('LOGICA DE PROGRAMAÇÃO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('LINGUAGEM DE PROGRAMACAO II', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('LINGUAGEM SQL', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('TECNOLOGIA WEB', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('AMBIENTE E DESENVOLVIMENTO DE OPERAÇÃO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('SOCIEDADE E SUSTENTABILIDADE', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('LIBRAS', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('DESENVOLVIMENTO DE APLICAÇÕES DISTRIBUIDAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('INTERFACE HOMEM-COMPUTADOR', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('ARQUUITETURA E PROJETO DE SISTEMAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('DESENVOLVIMENTO PARA DISPOSITIVOS MOVEIS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('LEGISLAÇÃO E ÉTICA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('DEVELOPING DATABASE', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('BUSINESS INTELLIGENCE', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('DATA ANALYTICS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('ADMINISTRAÇÃO DE BANCO DE DADOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('QUALIDADE DE GOVERNANCA DE DADOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('SEGURANCA DE BANCO DE DADOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('BIG DATA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('CIRCUITOS DIGITAIS E ELETRONICOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('IOT', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('MATEMATICA PARA ENGENHARIA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('DEVOPS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('CONCEITO E APLICAÇOES DE CALCULOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('ENGENHARIA DE SOFTWARE', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('CIENCIAS DO AMBIENTE', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('DESENVOLVIMENTO DE APLICACOES DISTRIBUIDAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('ENGENHARIA DE REQUISITOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('MODELAGEM E SIMULACAO DE SISTEMAS FISICOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('CIRCUITOS ELETRICOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('ELETRICIDADE E MAGNETISMO APLICADOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('MATEMATICA DISCRETA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('OTIMIZAÇÃO DE SISTEMAS LINEARES', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('ANALISE NUMERICA', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('ARQUITETURA DE COMPUTADORES E SISTEMAS OPERACIONAIS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('ELETRONICA ANALOGICA E DIGITAL', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('LINGUAGENS FORMAIS E AUTOMATOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('PROCESSAMENTO DIGITAL DE SINAIS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('ANALISE E VIABILIDADE DE PROJETOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('COMPILADORES', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('CONTROLE E AUTOMAÇÃO ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('GESTÃO AGIL DE PROJETOS', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('INTELIGENCIA ARTIFICIAL', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('SISTEMAS DISTRIBUIDOS E CLOUD COMPUTING', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('ECONOMIA PARA ENGENHARIA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('ROBOS MOVEIS INTELIGENTES', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('SEGURANCA CIBERNETICA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('STARTUP E INOVACAO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('UX E DESIGN THINKING', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('INDUSTRIA 4.0', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('LEGISLACÃO E ETICA', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('PROJETO DE SISTEMAS EMBARCADOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('SISTEMAS TOLERANTES A FALHAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('TOPICOS ESPECIAIS EM TENDENCIAS TECNOLOGICAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('BANCO DE DADOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('LINGUAGEM DE PROGRAMACAO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('SISTEMAS INTEGRADOS A GESTÃO','PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('GESTÃO DE PROJETOS','PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('MODELAGEM DE PROCESSOS DE NOGOCIO','PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('QUALIDADE DE SOFTWARE', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('LEGISLACAO E ETICA', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('GESTÃO ESTRATEGIA DE TI','PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('GESTÃO DE INFRAESTURA DE TI','PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('GESTÃO DA SEGURANCA DA INFORMAÇÃO','PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('GOVERNANCA DE TI', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3)





--CADASTRO DISCIPLINA(RAFAEL)

--PARTE SHIPS

INSERT INTO DISCIPLINAOFERTADA(IDCOORDENADOR,DTINICIOMATRICULA,DTFIMMATRICULA,IDDISCIPLINA,IDCURSO,ANO,SEMESTRE,TURMA,IDPROFESSOR,METODOLOGIA,RECURSOS,CRITERIOAVALIACAO,PLANODEAULAS)
VALUES																	
(1,'2018-01-01','2018-05-01',1,1,'2018',2,'A',1,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',2,1,'2018',2,'A',2,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',3,1,'2018',2,'A',3,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',4,1,'2018',2,'A',4,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',5,1,'2018',2,'A',5,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',6,1,'2018',2,'A',6,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',7,1,'2018',2,'A',7,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',8,1,'2018',2,'A',8,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),

(1,'2018-01-01','2018-05-01',1,1,'2018',2,'B',1,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',2,1,'2018',2,'B',2,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',3,1,'2018',2,'B',3,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',4,1,'2018',2,'B',4,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',5,1,'2018',2,'B',5,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',6,1,'2018',2,'B',6,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',7,1,'2018',2,'B',7,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(1,'2018-01-01','2018-05-01',8,1,'2018',2,'B',8,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),



(2,'2018-01-01','2018-05-01',1,2,'2018',2,'A',1,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',2,2,'2018',2,'A',2,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',3,2,'2018',2,'A',3,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',4,2,'2018',2,'A',4,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',5,2,'2018',2,'A',5,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',6,2,'2018',2,'A',6,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',7,2,'2018',2,'A',7,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',8,2,'2018',2,'A',8,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),

(2,'2018-01-01','2018-05-01',1,2,'2018',2,'B',1,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',2,2,'2018',2,'B',2,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',3,2,'2018',2,'B',3,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',4,2,'2018',2,'B',4,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',5,2,'2018',2,'B',5,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',6,2,'2018',2,'B',6,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',7,2,'2018',2,'B',7,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',8,2,'2018',2,'B',8,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),

(2,'2018-01-01','2018-05-01',1,2,'2018',2,'C',1,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',2,2,'2018',2,'C',2,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',3,2,'2018',2,'C',3,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',4,2,'2018',2,'C',4,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',5,2,'2018',2,'C',5,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',6,2,'2018',2,'C',6,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',7,2,'2018',2,'C',7,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',8,2,'2018',2,'C',8,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),

(2,'2018-01-01','2018-05-01',1,2,'2018',2,'D',1,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',2,2,'2018',2,'D',2,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',3,2,'2018',2,'D',3,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',4,2,'2018',2,'D',4,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',5,2,'2018',2,'D',5,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',6,2,'2018',2,'D',6,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',7,2,'2018',2,'D',7,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' ),
(2,'2018-01-01','2018-05-01',8,2,'2018',2,'D',8,'avaliar capacidades','em sala de aula','provas e acs de 0 a 10','começa no ano letivo e acaba no final . . .' );



INSERT INTO SOLICITACAOMATRICULA(IDALUNO,IDDOFERTADA,IDCOORDENADOR,STATUS)
VALUES
(1,1,1,'SOLICITADA'),
(2,1,1,'SOLICITADA'),
(3,1,1,'SOLICITADA'),
(4,1,1,'SOLICITADA'),
(5,1,1,'SOLICITADA'),
(6,1,1,'SOLICITADA'),
(7,1,1,'SOLICITADA'),
(8,1,1,'SOLICITADA'),
(9,1,1,'SOLICITADA'),
(10,1,1,'SOLICITADA'),

(1,1,1,'APROVADA'),
(2,1,1,'APROVADA'),
(3,1,1,'APROVADA'),
(4,1,1,'APROVADA'),
(5,1,1,'APROVADA'),
(6,1,1,'APROVADA'),
(7,1,1,'APROVADA'),
(8,1,1,'APROVADA'),
(9,1,1,'APROVADA'),
(10,1,1,'APROVADA'),

(1,1,1,'REJEITADA'),
(2,1,1,'REJEITADA'),
(3,1,1,'REJEITADA'),
(4,1,1,'REJEITADA'),
(5,1,1,'REJEITADA'),
(6,1,1,'REJEITADA'),
(7,1,1,'REJEITADA'),
(8,1,1,'REJEITADA'),
(9,1,1,'REJEITADA'),
(10,1,1,'REJEITADA'),

(1,1,1,'CANCELADA'),
(2,1,1,'CANCELADA'),
(3,1,1,'CANCELADA'),
(4,1,1,'CANCELADA'),
(5,1,1,'CANCELADA'),
(6,1,1,'CANCELADA'),
(7,1,1,'CANCELADA'),
(8,1,1,'CANCELADA'),
(9,1,1,'CANCELADA'),
(10,1,1,'CANCELADA');


INSERT INTO ATIVIDADE(TITULO,DESCRICAO,CONTEUDO,TIPO,EXTRAS,IDPROFESSOR)
VALUES
('ac1','atividades da ac1','bla bla bla','RESPOSTA ABERTA','',1),
('ac2','atividades da ac2','bla bla bla','RESPOSTA ABERTA','',1),
('ac3','atividades da ac3','bla bla bla','RESPOSTA ABERTA','',1),
('ac4','atividades da ac4','bla bla bla','RESPOSTA ABERTA','',1),
('ac5','atividades da ac5','bla bla bla','RESPOSTA ABERTA','',1),
('ac6','atividades da ac6','bla bla bla','RESPOSTA ABERTA','',1),
('ac7','atividades da ac7','bla bla bla','RESPOSTA ABERTA','',1),
('ac8','atividades da ac8','bla bla bla','RESPOSTA ABERTA','',1),
('ac9','atividades da ac9','bla bla bla','RESPOSTA ABERTA','',1),
('ac10','atividades da ac1','bla bla bla','RESPOSTA ABERTA','',1);









--PARTE IZA

INSERT INTO ATIVIDADEVINCULADA
(IDATIVIDADE, IDPROFESSOR, IDDOFERTADA, ROTULO, STATUS, DTINIRESPOSTA, DTFIMRESPOSTA)
VALUES
(1,1,1,'COMUNICAÇÃO', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(2,2,1,'COMUNICAÇÃO', 'ABERTA', GETDATE(), GETDATE()+30 ),
(3,3,3,'COMUNICAÇÃO', 'FECHADA', GETDATE(), GETDATE()+30 ),
(4,4,4,'COMUNICAÇÃO', 'ENCERRADA', GETDATE(), GETDATE()+30 ),
(5,5,5,'COMUNICAÇÃO', 'PRORROGADA', GETDATE(), GETDATE()+30 ),
(6,6,6,'COMUNICAÇÃO', 'FECHADA', GETDATE(), GETDATE()+30 ),
(7,7,7,'COMUNICAÇÃO', 'PRORROGADA', GETDATE(), GETDATE()+30 ),
(8,8,4,'COMUNICAÇÃO', 'ABERTA', GETDATE(), GETDATE()+30 ),
(9,9,4,'COMUNICAÇÃO', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(10,10,10,'COMUNICAÇÃO', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(2,11,11,'COMUNICAÇÃO', 'ABERTA', GETDATE(), GETDATE()+30 ),
(3,12,12,'COMUNICAÇÃO', 'ABERTA', GETDATE(), GETDATE()+30 ),
(5,13,13,'COMUNICAÇÃO', 'FECHADA', GETDATE(), GETDATE()+30 ),
(1,14,14,'COMUNICAÇÃO', 'PRORROGADA', GETDATE(), GETDATE()+30 ),
(6,15,15,'COMUNICAÇÃO', 'PRORROGADA', GETDATE(), GETDATE()+30 ),
(7,16,16,'COMUNICAÇÃO', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(8,17,17,'COMUNICAÇÃO', 'FECHADA', GETDATE(), GETDATE()+30 ),
(9,18,18,'COMUNICAÇÃO', 'FECHADA', GETDATE(), GETDATE()+30 ),
(10,19,19,'COMUNICAÇÃO', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(4,20,20,'COMUNICAÇÃO', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 );


INSERT INTO ENTREGA 
(IDALUNO, IDAVINCULADA, TITULO, RESPOSTA, DTENTREGA, STATUS, IDPROFESSOR, NOTA, DTAVALIACAO, OBS)
VALUES
(1, 1, 'ENTREGA AC1', '1-C, 2-A, 3-B',2018-06-01,'CORRIGIDO', 1, 10, GETDATE(),'FOI UM POUCO DIFICIL'),
(2, 1, 'ENTREGA AC1', '1-C, 2-A, 3-B',2018-06-01,'CORRIGIDO', 1, 5, GETDATE(),'MUITO DIFICIL'),
(3, 2, 'ENTREGA AC2', '1-A, 2-C, 3-B',2018-06-08,'CORRIGIDO', 2, 9, GETDATE(),'NAO TIVE TANTA DIFICULDADE'), 
(4, 2, 'ENTREGA AC2', '1-A, 2-C, 3-B',2018-06-08,'CORRIGIDO', 2, 3, GETDATE(),'GOSTARIA DE FAZER NOVAMENTE'),
(5, 3, 'ENTREGA AC3', '1-B, 2-C, 3-A',2018-06-15,'CORRIGIDO', 3, 6, GETDATE(),'FOI UM POUCO DIFICIL'),
(6, 3, 'ENTREGA AC3', '1-B, 2-C, 3-A',2018-06-15,'CORRIGIDO', 3, 10, GETDATE(),'FACIL'),
(7, 4, 'ENTREGA AC4', '1-A, 2-B, 3-C',2018-06-22,'CORRIGIDO', 4, 1, GETDATE(),'NAO SABIA'),
(8, 4, 'ENTREGA AC4', '1-A, 2-B, 3-C',2018-06-22,'CORRIGIDO', 4, 0, GETDATE(),'FALTEI'),
(9, 5, 'ENTREGA AC5', '1-C, 2-A, 3-B',2018-06-29,'CORRIGIDO', 5, 7, GETDATE(),'GOSTARIA DE TER IDO MELHOR'),
(10, 5,'ENTREGA AC5', '1-C, 2-A, 3-B',2018-06-29,'CORRIGIDO', 5, 10, GETDATE(),'FUI MUITO BEM'),
(11, 6, 'ENTREGA AC6', '1-B, 2-C, 3-A',2018-07-10,'CORRIGIDO', 6, 3, GETDATE(),'FUI PESSIMO'),
(12, 6, 'ENTREGA AC6', '1-B, 2-C, 3-A',2018-07-10,'CORRIGIDO', 6, 4, GETDATE(),'VOU ESTUDAR MAIS')

INSERT INTO ENTREGA 
(IDALUNO, IDAVINCULADA, TITULO, RESPOSTA, STATUS)
VALUES
(21, 7, 'ENTREGA AC7', '1-B, 2-C, 3-A','ENTREGUE'),
(25, 7,  'ENTREGA AC7', '1-B, 2-C, 3-A','ENTREGUE'),
(26, 8,  'ENTREGA AC8', '1-A, 2-C, 3-B','ENTREGUE' ),
(30, 8, 'ENTREGA AC8', '1-A, 2-C, 3-B','ENTREGUE' ),
(40, 9, 'ENTREGA AC9', '1-C, 2-B, 3-A','ENTREGUE' ),
(50, 9, 'ENTREGA AC9', '1-C, 2-B, 3-A','ENTREGUE' ),
(49, 10, 'ENTREGA AC10', '1-A, 2-C, 3-B','ENTREGUE'),
(32, 10, 'ENTREGA AC10', '1-A, 2-C, 3-B','ENTREGUE' ),
(1, 11, 'ENTREGA AC11', '1-B, 2-C, 3-A','ENTREGUE' ),
(2, 11, 'ENTREGA AC11', '1-B, 2-C, 3-A','ENTREGUE' ),
(3, 12, 'ENTREGA AC12', '1-C, 2-B, 3-A','ENTREGUE'),
(4, 12, 'ENTREGA AC12', '1-C, 2-B, 3-A','ENTREGUE' ),
(5, 13, 'ENTREGA AC13', '1-A, 2-B, 3-C','ENTREGUE'),
(6, 13, 'ENTREGA AC13', '1-A, 2-B, 3-C','ENTREGUE'),
(7, 14, 'ENTREGA AC14', '1-B, 2-C, 3-A','ENTREGUE'),
(8, 14, 'ENTREGA AC14', '1-B, 2-C, 3-A','ENTREGUE' ),
(9, 15,'ENTREGA AC15', '1-C, 2-A, 3-B','ENTREGUE' ),
(10, 15, 'ENTREGA AC15', '1-C, 2-A, 3-B','ENTREGUE'),
(11, 16,'ENTREGA AC16', '1-A, 2-C, 3-B','ENTREGUE'),
(12, 16, 'ENTREGA AC16', '1-A, 2-A, 3-B','ENTREGUE'),
(13, 17, 'ENTREGA AC17', '1-A, 2-A, 3-B','ENTREGUE' ),
(14, 17,'ENTREGA AC17', '1-B, 2-C, 3-A','ENTREGUE'),
(15, 18, 'ENTREGA AC18', '1-C, 2-A, 3-B','ENTREGUE'),
(16, 18,'ENTREGA AC18', '1-C, 2-A, 3-B','ENTREGUE'),
(17, 19, 'ENTREGA AC19', '1-A, 2-A, 3-B','ENTREGUE'),
(18, 19, 'ENTREGA AC19', '1-A, 2-A, 3-B','ENTREGUE'),
(19, 20,'ENTREGA AC20', '1-C, 2-B, 3-B','ENTREGUE'),
(20, 20,'ENTREGA AC20', '1-C, 2-B, 3-B','ENTREGUE');


INSERT INTO MENSAGEM
 (IDALUNO, IDPROFESSOR, ASSUNTO, REFERENCIA, CONTEUDO, STATUS, DTENVIO, DTRESPOSTA, RESPOSTA)
VALUES
(1, 1,'COMUNICACAO E EXPRESSAO', 'FALTA', 'PROFESSOR FAVOR VERIFICAR MINHA FALTA DO DIA 10/07', 'RESPONDIDO', 2018-07-12,2018-07-15,'FALTA LANÇADA ERRONEAMENTE, JÁ AJUSTADO. FAVOR VERFIQUE'),
(2, 2,'MSG', 'EAD','VAI TER AULA DIA 20','RESPONDIDO',2018-05-13, 2018-05-14, 'SIM IRA TER'),
(3, 3,'DUVIDA', 'PROVA','QUAL FOI A MINHA NOTA ?','RESPONDIDO',2018-05-26, 2018-05-27, 'SO POSSO INFORMAR DIA 30'),
(4, 4,'MSG', 'FERIAS','QUANDO IRA SER AS FERIAS','RESPONDIDO',2018-05-30, 2018-06-1, 'SIM IRA TER'),
(5, 5,'MSG', 'PROVA','QUAL VAI SER O DIA DA PROVA','RESPONDIDO',2018-06-01, 2018-06-02, 'SIM IRA TER'),
(6, 6,'MSG', 'TRABALHO','ESSE TRABALHO VALE DE 0 A 10','RESPONDIDO',2018-06-13, 2018-06-14, 'SIM IRA TER'),
(7, 7,'MSG', 'FERIADO','PODEMOS ENTREGAR O TRABALHO NO FERIADO','RESPONDIDO',2018-06-15, 2018-05-16, 'SIM IRA TER'),
(8, 8,'MSG', 'PROFESSOR','PROFESSOR VC VAI AMANHA ?','RESPONDIDO',2018-05-13, 2018-05-14, 'SIM IRA TER'),
(9, 9,'MSG', 'EAD','VC RECEBEU O TRABALHO ?','RESPONDIDO',2018-07-13, 2018-07-14, 'SIM IRA TER'),
(10, 10,'MSG', 'FERIAS','QUANDO COMECA AS FERIAS','RESPONDIDO',2018-07-09, 2018-07-10, 'SIM IRA TER'),
(11, 11,'MSG', 'TRABALHO','JA ACABOU O TEMPO PARA ENTREGAR O TRABALHO','RESPONDIDO',2018-08-11, 2018-08-12, 'SIM IRA TER'),
(12, 12,'MSG', 'TRABALHO','PROFESSOR PODE ME PASSAR O TRABALHO EU FALTEI','RESPONDIDO',2018-08-20, 2018-08-21,'SIM'),
(13, 13,'MSG', 'PROFESSOR','VC IRA DIA 29','RESPONDIDO',2018-08-29, 2018-08-30,'SIM' ),
(14, 14,'MSG', 'FERIADO','NO PROXIMO FERIADO TERA PALESTRA','RESPONDIDO', 2018-05-20, 2018-05-21, 'SIM'),
(15, 15,'MSG', 'EAD','JA ENVIEI O TRABALHO','RESPONDIDO',2018-09-18, 2018-09-19, 'OK' ),
(16, 16,'MSG', 'FERIAS','VAI TER AULA DIA 20','RESPONDIDO',2018-05-13, 2018-05-14, 'SIM' ),
(17, 17,'MSG', 'EAD','POSSO ENTREGAR A ATIVIDADE UM POUCO ATRASADO','RESPONDIDO',2018-05-13, 2018-05-14, 'NAO' ),
(18, 18,'MSG', 'PROFESSOR','POSSE TE ENTREGAR AMANHA O TRABALHO','RESPONDIDO',2018-05-13, 2018-05-14, 'SIM' ),
(19, 19,'MSG', 'PROFESSOR','OBRIGADO PROFESSOR','RESPONDIDO',2018-05-13, 2018-05-14, 'DE NADA' ),
(20, 20,'MSG', 'FERIAS','AS AULAS ACABA AMANHA','RESPONDIDO',2018-10-25, 2018-10-26, 'NAO' ),

(22, 22,'MSG', 'BD','COMO DAR UM INSERT','RESPONDIDO',2018-10-13, 2018-10-14, 'NA AULA TE ESPLICO'),
(23, 23,'MSG', 'METERIA','PODE ME MANDAR O MATERIAL','RESPONDIDO',2018-08-13, 2018-08-14, 'JA ENVIAMOS' ),
(28, 28,'MSG', 'CALENDARIO','SABADO TERA PALESTRA','RESPONDIDO',2018-11-29, 2018-11-30, 'NAO ELA FOI CANCELADA'),
(29, 29,'MSG', 'CALENDARIO','NO PROXIMO FERIADO NAO POSSO ENTREGAR A AC','RESPONDIDO',2018-10-11,2018-10-12,'OK' ),
(30, 30,'MSG', 'CALENDARIO','ATE AMANHA','RESPONDIDO',2018-05-13,2018-05-14,'ATE');

INSERT INTO MENSAGEM
 (IDALUNO, IDPROFESSOR, ASSUNTO, REFERENCIA, CONTEUDO, STATUS, DTENVIO)
VALUES
(21, 21,'MSG', 'EAD','JA ENVIEI A AC','ENVIADO',2018-10-16),
(24, 24,'MSG', 'MATERIA','JA RECEBI O METRIAL','ENVIADO',2018-09-13 ),
(25, 25,'MSG', 'FERIAS','JA ESTOU DE FERIAS ?','ENVIADO',2018-10-19 ),
(26, 26,'MSG', 'PROFESSOR','VOCE IRA AMANHA','ENVIADO',2018-06-12 ),
(27, 27,'MSG', 'EAD','FUI APROVADO','ENVIADO',2018-11-30)

